Repository parkkyonghun/lc-opd-daily, pull requests merged in 2025-03, with the labels that each got.

#3 Implement Docker setup, update Next.js configuration, and enhance use…
  11.2.0
  Build
  Dockerfile
  docker-compose.yml
  docs/branch-rbac.md
  document/Enhancements.md
  document/Improment-context.md
  document/central-auth.md
  document/context.prod.md
  document/tasks-context.md
  next
  next.config.js
  scripts/deploy-lightsail.sh
  src/app/(dashboard)/dashboard/settings/page.tsx
  src/app/_actions/user.ts
  src/app/api/auth/register/route.ts
  src/app/api/branches/[id]/route.ts
  src/app/api/branches/route.ts
  src/app/api/consolidated/route.ts
  src/app/api/dashboard/charts/route.ts
  src/app/api/dashboard/data/route.ts
  src/app/api/dashboard/stats/route.ts
  src/app/api/health/route.ts
  src/app/api/reports/[id]/approve/route.ts
  src/app/api/reports/[id]/route.ts
  src/app/api/reports/route.ts
  src/app/api/roles/manage/route.ts
  src/app/api/roles/route.ts
  src/app/api/route.ts
  src/app/api/users/[id]/branch-assignments/route.ts
  src/app/api/users/[id]/branches/route.ts
  src/app/api/users/[id]/route.ts
  src/app/api/users/[id]/security/route.ts
  src/app/api/users/preferences/route.ts
  src/app/api/users/switch-branch/route.ts
  src/app/login/page.tsx
  src/components/dashboard/layout/DashboardLayout.tsx
  src/components/providers/ThemeProvider.tsx
  src/components/reports/CreateReportModal.tsx
  src/components/ui/form-example.tsx
  src/components/ui/form.tsx
  src/hooks/useFormValidation.ts
  src/lib/auth.ts
  src/lib/auth/index.ts
  src/lib/db.ts
  src/lib/utils.ts
  src/middleware/api-permission-guard.ts
Labels: bug, enhancement

#6 Refactor form validation in useReportForm hook
  src/hooks/useReportForm.ts
Labels: bug

#15 Enhance avatar handling and S3 integration
  next.config.js
  package-lock.json
  package.json
  src/app/(dashboard)/dashboard/profile/page.tsx
  src/app/(dashboard)/dashboard/settings/page.tsx
  src/app/api/users/avatar/route.ts
  src/app/profile/edit/page.tsx
  src/app/profile/page.tsx
  src/app/uploads/avatars/[...path]/route.ts
  src/components/dashboard/layout/TopBar.tsx
  src/contexts/UserDataContext.tsx
  src/lib/s3.ts
  src/middleware.ts
Labels: documentation, good first issue

#21 refactor(api): improve date formatting and query logic in consolidate…
  prisma/migrations/20250325023046_20240317_add_notifications/migration.sql
  src/app/api/consolidated/route.ts
  src/app/api/dashboard/data/route.ts
  src/components/consolidated-view.tsx
  src/lib/utils.ts
Labels: bug, invalid
